sentiment_analysis_app/config/routes.rb
Rails.application.routes.draw do
  root to: 'application#index'

  resources :sentiments, only: [:index, :show, :new, :create]
end

sentiment_analysis_app/app/models/sentiment.rb
class Sentiment < ActiveRecord::Base

	validates :text, presence: true
	validates :behavior, presence: true
	validates :rating, presence: true, numericality: true 

end 

sentiment_analysis_app/app/controllers/sentiments_controller.rb
class SentimentsController < ApplicationController

	def index
		@sentiments = Sentiment.all
	end

	def show
		@sentiment = Sentiment.find(params[:id])
	end

	def new
		@sentiment = Sentiment.new
	end

	def create
		@sentiment = Sentiment.new(sentiment_params)
		alchemyapi = AlchemyAPI.new
		result = alchemyapi.sentiment('text', @sentiment.text)
		behavior = result["docSentiment"]["type"]
		rating = result["docSentiment"]["score"]
		@sentiment.update({behavior: behavior, rating: rating})
		
		if @sentiment.save
			redirect_to @sentiment
		else
			render :new
		end
	end

	private
	def sentiment_params
		params.require(:sentiment).permit(:text, :behavior, :rating)
	end
end

sentiment_analysis_app/app/views/sentiments/index.html.erb
<div class="info" id="list">
	<hr>
	<% @sentiments.each do |sentiment| %>
			<%= sentiment.text %> | 
			<%= sentiment.behavior %> | 
			<%= sentiment.rating %>
		<hr>
	<% end %>
</div>

<h4 id="link">
	<%= link_to 'Homepage', root_path %> | 
	<%= link_to 'Post', new_sentiment_path %>
</h4>	

sentiment_analysis_app/app/views/sentiments/new.html.erb
<div class="info">
	<%= form_for @sentiment do |f| %>
		
		<%= f.label :text %>
		<%= f.text_field :text %>

		<%= f.submit 'Submit'%>

	<% end %>
</div>

<h4 id="link">
	<%= link_to 'Homepage', root_path %> | 
	<%= link_to 'Complete List', sentiments_path %>
</h4>

sentiment_analysis_app/app/views/sentiments/show.html.erb
<div class="info">
	<h2> <%= @sentiment.text %> </h2>
	<h2> <%= @sentiment.behavior %> </h2>
	<h2> <%= @sentiment.rating %> </h2>
</div>

<h4 id="link">
	<%= link_to 'Homepage', root_path %> | 
	<%= link_to 'Complete List', sentiments_path %> | 
	<%= link_to 'Back to Post', new_sentiment_path %> 
</h4>